steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east2-docker.pkg.dev/kindred-bi-reporting/cloud-run-source-deploy/ad_etl_repo_image', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east2-docker.pkg.dev/kindred-bi-reporting/cloud-run-source-deploy/ad_etl_repo_image']

images:
- 'asia-east2-docker.pkg.dev/kindred-bi-reporting/cloud-run-source-deploy/ad_etl_repo_image'

options:
  logging: CLOUD_LOGGING_ONLY